LAB_9/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab9_.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lab9_.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;

        public CustomerController(ICustomerRepository _customerRepository)
        {
            this._customerRepository = _customerRepository;
        }

        [AllowAnonymous]
        public IActionResult Home()
        {
            var model = _customerRepository.GetAllCustomer();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer model)
        {
            if (ModelState.IsValid)
            {
                Customer customer = new Customer()
                {
                    Name = model.Name,
                    Email = model.Email,
                    MobileNo = model.MobileNo
                };
                _customerRepository.Add(customer);
               
                return RedirectToAction("Home");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _customerRepository.GetCustomer(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(Customer model)
        {
            Customer customer = _customerRepository.GetCustomer(model.Id);
            customer.Name = model.Name;
            customer.Email = model.Email;
            customer.MobileNo = model.MobileNo;
            _customerRepository.Update(customer);
            return RedirectToAction("Home");
        }
        public IActionResult Delete(int id)
        {
            _customerRepository.Delete(id);
            return RedirectToAction("Home");
        }
    }
}

LAB_9/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab9_.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lab9_.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        public OrderController(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;
        }

        [AllowAnonymous]
        public IActionResult Home()
        {
            IEnumerable<Order> model = _orderRepository.GetAllOrders();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Order model)
        {
            if (ModelState.IsValid)
            {
                Order order = new Order()
                {
                    CustomerId = model.CustomerId,
                    ProductId=model.ProductId,
                    Amount=model.Amount,
                    OrderDate=model.OrderDate
                };
                _orderRepository.Add(order);
                return RedirectToAction("Home");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _orderRepository.GetOrder(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Order model)
        {
            Order order = _orderRepository.GetOrder(model.Id);
            order.Amount = model.Amount;
            order.CustomerId = model.CustomerId;
            order.ProductId = model.ProductId;
            order.OrderDate = model.OrderDate;
            _orderRepository.Update(order);
            return RedirectToAction("Home");
        }

        public IActionResult Delete(int id)
        {
            _orderRepository.Delete(id);
            return RedirectToAction("Home");
        }
    }
}

LAB_9/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lab9_.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lab9_.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _ProductRepository;

        public ProductController(IProductRepository _ProductRepository)
        {
            this._ProductRepository = _ProductRepository;
        }

        [AllowAnonymous]
        public IActionResult Home()
        {
            var model = _ProductRepository.GetAllProducts();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product model)
        {
            if (ModelState.IsValid)
            {
                Product Product = new Product()
                {
                    Name = model.Name,
                    Details=model.Details,
                    Price=model.Price
                };
                _ProductRepository.Add(Product);

                return RedirectToAction("Home");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _ProductRepository.GetProduct(id);
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(Product model)
        {
            Product product= _ProductRepository.GetProduct(model.Id);
            product.Name = model.Name;
            product.Details = model.Details;
            product.Price = model.Price;
            _ProductRepository.Update(product);
            return RedirectToAction("Home");
        }
        public IActionResult Delete(int id)
        {
            _ProductRepository.Delete(id);
            return RedirectToAction("Home");
        }
    }
}

LAB_9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.pageTitle</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-dark navbar-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Order Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav"> 
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Home">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Home">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Home">Orders</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <button type="submit" class="nav-link btn btn-link py-0">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Lab9_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>